// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cert} from '../models';
import {cache} from '../models';
import {migration} from '../models';
import {service} from '../models';
import {main} from '../models';

export function CancelMigration():Promise<void>;

export function CertificateStatus():Promise<cert.Status>;

export function ChangeCacheRoot(arg1:string):Promise<void>;

export function ChooseCacheRoot():Promise<string>;

export function ClearCache():Promise<void>;

export function ClearLogs():Promise<void>;

export function GetCloseBehavior():Promise<string>;

export function GetStartupEnabled():Promise<boolean>;

export function InspectCache():Promise<cache.HealthReport>;

export function InstallCertificate():Promise<void>;

export function MigrationStatus():Promise<migration.Status>;

export function OpenCacheFolder():Promise<void>;

export function OpenConfigFolder():Promise<void>;

export function PauseMigration():Promise<void>;

export function RegenerateCertificate():Promise<void>;

export function ResumeMigration():Promise<void>;

export function SetCloseBehavior(arg1:string):Promise<void>;

export function SetListenPort(arg1:number):Promise<void>;

export function SetNetworkMode(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string,arg6:string):Promise<void>;

export function SetStartupEnabled(arg1:boolean):Promise<void>;

export function Snapshot():Promise<service.Snapshot>;

export function Start():Promise<void>;

export function Stop():Promise<void>;

export function TestConnection():Promise<main.ConnectionTestResult>;

export function UninstallCertificate():Promise<void>;
