// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelMigration() {
  return window['go']['main']['App']['CancelMigration']();
}

export function CertificateStatus() {
  return window['go']['main']['App']['CertificateStatus']();
}

export function ChangeCacheRoot(arg1) {
  return window['go']['main']['App']['ChangeCacheRoot'](arg1);
}

export function ChooseCacheRoot() {
  return window['go']['main']['App']['ChooseCacheRoot']();
}

export function ClearCache() {
  return window['go']['main']['App']['ClearCache']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function GetStartupEnabled() {
  return window['go']['main']['App']['GetStartupEnabled']();
}

export function InspectCache() {
  return window['go']['main']['App']['InspectCache']();
}

export function InstallCertificate() {
  return window['go']['main']['App']['InstallCertificate']();
}

export function MigrationStatus() {
  return window['go']['main']['App']['MigrationStatus']();
}

export function OpenCacheFolder() {
  return window['go']['main']['App']['OpenCacheFolder']();
}

export function OpenConfigFolder() {
  return window['go']['main']['App']['OpenConfigFolder']();
}

export function PauseMigration() {
  return window['go']['main']['App']['PauseMigration']();
}

export function RegenerateCertificate() {
  return window['go']['main']['App']['RegenerateCertificate']();
}

export function ResumeMigration() {
  return window['go']['main']['App']['ResumeMigration']();
}

export function SetNetworkMode(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SetNetworkMode'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SetStartupEnabled(arg1) {
  return window['go']['main']['App']['SetStartupEnabled'](arg1);
}

export function Snapshot() {
  return window['go']['main']['App']['Snapshot']();
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function TestConnection() {
  return window['go']['main']['App']['TestConnection']();
}

export function UninstallCertificate() {
  return window['go']['main']['App']['UninstallCertificate']();
}
